ALTER TABLE blood_sugar_logs
    ADD COLUMN IF NOT EXISTS severity VARCHAR(50) NOT NULL DEFAULT 'normal',
    ADD COLUMN IF NOT EXISTS reference_min INT NOT NULL DEFAULT 70,
    ADD COLUMN IF NOT EXISTS reference_max INT NOT NULL DEFAULT 140,
    ADD COLUMN IF NOT EXISTS reference_range VARCHAR(100),
    ADD COLUMN IF NOT EXISTS recommendation TEXT,
    ADD COLUMN IF NOT EXISTS color VARCHAR(30);
