ALTER TABLE patients ADD COLUMN IF NOT EXISTS patient_code VARCHAR(50);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS diagnosis_date DATE;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS current_medication TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS allergies TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS smoking_status VARCHAR(50);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS physical_activity_level VARCHAR(50);
